- name: Initialize Vault KV and store secrets
        run: |
          until docker exec skills_utilization-vault-1 vault status > /dev/null 2>&1; do
            echo "Waiting for Vault..."
            sleep 1
          done
          docker exec -e VAULT_ADDR='http://127.0.0.1:8200' skills_utilization-vault-1 vault secrets enable -path=kv kv-v2 || true
          docker exec -e VAULT_ADDR='http://127.0.0.1:8200' skills_utilization-vault-1 vault kv put kv/project3 DB_PASSWORD="devpassword123" SECRET_KEY="supersecret"
